api_platform:
    title: Hello API Platform
    version: 1.0.0
    eager_loading:
        force_eager: false
        max_joins: 5 # Augmentez cette valeur selon vos besoins
    defaults:
        stateless: true
