version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_api_ldveh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=dev
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8.0
    container_name: mysql_ldveh
    restart: always
    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ldveh
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
